<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_boulder',
		'title' => 'Boulder',
		'fields' => array (
			array (
				'key' => 'field_5a108c3a99126',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 30,
			),
			array (
				'key' => 'field_5a108c7999127',
				'label' => 'Grade',
				'name' => 'grade',
				'type' => 'select',
				'choices' => array (
					'VB' => 'VB',
					'V0' => 'V0',
					'V1' => 'V1',
					'V2' => 'V2',
					'V3' => 'V3',
					'V4' => 'V4',
					'V5' => 'V5',
					'V6' => 'V6',
					'V7' => 'V7',
					'V8' => 'V8',
					'V9' => 'V9',
					'V10' => 'V10',
					'V11' => 'V11',
					'V12' => 'V12',
					'V13' => 'V13',
					'V14' => 'V14',
					'V15' => 'V15',
					'V16' => 'V16',
					'V17' => 'V17',
					'' => '',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a108d1699128',
				'label' => 'First Ascent Climbers',
				'name' => 'first_ascent_climbers',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'First Ascent Climber',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 35,
			),
			array (
				'key' => 'field_5a108d4399129',
				'label' => 'First Ascent Date',
				'name' => 'first_ascent_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5a108d8c9912a',
				'label' => 'Area',
				'name' => 'area',
				'type' => 'taxonomy',
				'taxonomy' => 'area',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a108df026d1c',
				'label' => 'Boulder',
				'name' => 'boulder',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'boulder',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gaston_climb',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>